[package]
name = "verifier"
version = "1.1.0"
edition = "2024"

[dependencies]
temu_core = { path = "../core" }
vulnerability = { path = "../vulnerability" }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
tempfile = "3"
