[package]
name = "reporter"
version = "1.1.0"
edition = "2024"

[dependencies]
temu_core = { path = "../core" }
fingerprint = { path = "../fingerprint" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
tera = { workspace = true }
printpdf = { workspace = true }

[dev-dependencies]
tempfile = "3"
