[package]
name = "discovery"
version = "1.2.1"
edition = "2024"

[dependencies]
temu_core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
hickory-resolver = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
tokio = { workspace = true }
tempfile = "3"
